spring.application.name=aggregare
spring.output.ansi.enabled=always
spring.profiles.active=test
spring.jpa.open-in-view=true

api.security.jwt.secret=${JWT_SECRET}
api.security.jwt.expiration=${JWT_EXPIRATION}
api.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

admin.initial-username=${ADMIN_INITIAL_USERNAME}
admin.initial-password=${ADMIN_INITIAL_PASSWORD}
