spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.jwt.secret=3MVDikS8/m8o0Ivt2ducSWgo7d50RHBAS8KmNBO2d1I=
api.security.jwt.expiration=2h
api.security.cookie.secure=false
api.cors.allowed-origins=http://localhost:5173

admin.initial-username=admin
admin.initial-password=admin

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
