# Datasource PostgreSQL (local values)
spring.datasource.url=jdbc:postgresql://localhost:5432/abm
spring.datasource.username=abm
spring.datasource.password=abm
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Security (local values)
api.security.jwt.secret=3MVDikS8/m8o0Ivt2ducSWgo7d50RHBAS8KmNBO2d1I=
api.security.jwt.expiration=2h
api.security.cookie.secure=false
api.cors.allowed-origins=http://localhost:5173

# Initial admin credentials (local values)
admin.initial-username=admin
admin.initial-password=admin
