
    create table tb_address (
        client_id bigint unique,
        id bigint generated by default as identity,
        cep varchar(255),
        city varchar(255) not null,
        complement varchar(255),
        neighborhood varchar(255) not null,
        number varchar(255) not null,
        state varchar(255) not null,
        street varchar(255) not null,
        primary key (id)
    );

    create table tb_category (
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    create table tb_client (
        id bigint generated by default as identity,
        cpf_cnpj varchar(255),
        email varchar(255),
        name varchar(255) not null,
        name_normalized varchar(255) not null,
        primary key (id)
    );

    create table tb_expense (
        date date not null,
        due_date date,
        expense_value numeric(38,2) not null,
        payment_date date,
        id bigint generated by default as identity,
        category varchar(255) not null,
        name varchar(255) not null,
        payment_status enum ('PAID','PARTIAL','PENDING') not null,
        type enum ('FIXED','FUEL','VARIABLE') not null,
        primary key (id)
    );

    create table tb_fixed_expense (
        default_value numeric(38,2) not null,
        id bigint generated by default as identity,
        category varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table tb_fuel (
        km_driven float(53),
        liters float(53),
        price_per_liter float(53),
        expense_id bigint unique,
        id bigint generated by default as identity,
        fuel_supplier varchar(255),
        vehicle varchar(255),
        primary key (id)
    );

    create table tb_order (
        m3quantity float(53),
        order_value numeric(38,2) not null,
        remaining_value numeric(38,2) not null,
        scheduled_date date not null,
        scheduled_time time(6) not null,
        ton_quantity float(53),
        address_id bigint not null unique,
        client_id bigint not null,
        id bigint generated by default as identity,
        product_id bigint,
        observations varchar(255),
        service varchar(255),
        payment_status enum ('PAID','PARTIAL','PENDING') not null,
        status enum ('DELIVERED','PENDING') not null,
        type enum ('MATERIAL','SERVICE') not null,
        primary key (id)
    );

    create table tb_order_address (
        id bigint generated by default as identity,
        cep varchar(255),
        city varchar(255) not null,
        complement varchar(255),
        neighborhood varchar(255) not null,
        number varchar(255) not null,
        state varchar(255) not null,
        street varchar(255) not null,
        primary key (id)
    );

    create table tb_payment (
        date date not null,
        payment_value numeric(38,2) not null,
        id bigint generated by default as identity,
        order_id bigint,
        payment_method enum ('BANK_SLIP','BANK_TRANSFER','CASH','CHECK','CREDIT_CARD','DEBIT_CARD','PIX') not null,
        primary key (id)
    );

    create table tb_phone (
        client_id bigint,
        id bigint generated by default as identity,
        number varchar(255) not null,
        type enum ('CELULAR','FIXO','OUTRO','WHATSAPP') not null,
        primary key (id)
    );

    create table tb_price (
        m3volume integer not null,
        price float(53) not null,
        category_id bigint,
        id bigint generated by default as identity,
        primary key (id)
    );

    create table tb_product (
        category_id bigint,
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    create table tb_product_supplier (
        cost_for5cubic_meters float(53) not null,
        cost_per_cubic_meter float(53) not null,
        density float(53) not null,
        ton_cost float(53) not null,
        id bigint generated by default as identity,
        product_id bigint,
        supplier_id bigint,
        observations varchar(255),
        primary key (id)
    );

    create table tb_settings (
        id bigint not null,
        business_img_name varchar(255),
        business_name varchar(255) not null,
        primary key (id)
    );

    create table tb_stock (
        density float(53),
        m3quantity float(53) not null,
        ton_quantity float(53) not null,
        id bigint generated by default as identity,
        product_id bigint unique,
        version bigint,
        primary key (id)
    );

    create table tb_supplier (
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    create table tb_user (
        admin boolean,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        first_name varchar(255) not null,
        img_name varchar(255),
        last_name varchar(255) not null,
        password varchar(255) not null,
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists tb_address 
       add constraint FKmgkeodciwq4rofwws5m08v1yh 
       foreign key (client_id) 
       references tb_client;

    alter table if exists tb_fuel 
       add constraint FK5yca114jwhbc83jjghj4u9yf9 
       foreign key (expense_id) 
       references tb_expense;

    alter table if exists tb_order 
       add constraint FK7c9of0p9ogx0w8sfrebt4n9kk 
       foreign key (client_id) 
       references tb_client;

    alter table if exists tb_order 
       add constraint FKsga7o5cimuognsexkhgro0dak 
       foreign key (address_id) 
       references tb_order_address;

    alter table if exists tb_order 
       add constraint FKse6ptij0s2pp2nnbji87ivv46 
       foreign key (product_id) 
       references tb_product;

    alter table if exists tb_payment 
       add constraint FKokaf4il2cwit4h780c25dv04r 
       foreign key (order_id) 
       references tb_order;

    alter table if exists tb_phone 
       add constraint FK9bn3n1ykkraxjaw5y2qpqmby 
       foreign key (client_id) 
       references tb_client;

    alter table if exists tb_price 
       add constraint FKs94hpi9urs4n00nqd02peg4ys 
       foreign key (category_id) 
       references tb_category;

    alter table if exists tb_product 
       add constraint FK8i0sq9mfbpsrabrm2pum9fspo 
       foreign key (category_id) 
       references tb_category;

    alter table if exists tb_product_supplier 
       add constraint FKhm9dbkht6uggfk477bmuhlkq4 
       foreign key (product_id) 
       references tb_product;

    alter table if exists tb_product_supplier 
       add constraint FKsuny6mdqxe9u2mkikv5eudgor 
       foreign key (supplier_id) 
       references tb_supplier;

    alter table if exists tb_stock 
       add constraint FKrfkerq4he7y1d1rj97u8c77sf 
       foreign key (product_id) 
       references tb_product;

    create table tb_address (
        client_id bigint unique,
        id bigint generated by default as identity,
        cep varchar(255),
        city varchar(255) not null,
        complement varchar(255),
        neighborhood varchar(255) not null,
        number varchar(255) not null,
        state varchar(255) not null,
        street varchar(255) not null,
        primary key (id)
    );

    create table tb_category (
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    create table tb_client (
        id bigint generated by default as identity,
        cpf_cnpj varchar(255),
        email varchar(255),
        name varchar(255) not null,
        name_normalized varchar(255) not null,
        primary key (id)
    );

    create table tb_expense (
        date date not null,
        due_date date,
        expense_value numeric(38,2) not null,
        payment_date date,
        id bigint generated by default as identity,
        category varchar(255) not null,
        name varchar(255) not null,
        payment_status enum ('PAID','PARTIAL','PENDING') not null,
        type enum ('FIXED','FUEL','VARIABLE') not null,
        primary key (id)
    );

    create table tb_fixed_expense (
        default_value numeric(38,2) not null,
        id bigint generated by default as identity,
        category varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table tb_fuel (
        km_driven float(53),
        liters float(53),
        price_per_liter float(53),
        expense_id bigint unique,
        id bigint generated by default as identity,
        fuel_supplier varchar(255),
        vehicle varchar(255),
        primary key (id)
    );

    create table tb_order (
        m3quantity float(53),
        order_value numeric(38,2) not null,
        remaining_value numeric(38,2) not null,
        scheduled_date date not null,
        scheduled_time time(6) not null,
        ton_quantity float(53),
        address_id bigint not null unique,
        client_id bigint not null,
        id bigint generated by default as identity,
        product_id bigint,
        observations varchar(255),
        service varchar(255),
        payment_status enum ('PAID','PARTIAL','PENDING') not null,
        status enum ('DELIVERED','PENDING') not null,
        type enum ('MATERIAL','SERVICE') not null,
        primary key (id)
    );

    create table tb_order_address (
        id bigint generated by default as identity,
        cep varchar(255),
        city varchar(255) not null,
        complement varchar(255),
        neighborhood varchar(255) not null,
        number varchar(255) not null,
        state varchar(255) not null,
        street varchar(255) not null,
        primary key (id)
    );

    create table tb_payment (
        date date not null,
        payment_value numeric(38,2) not null,
        id bigint generated by default as identity,
        order_id bigint,
        payment_method enum ('BANK_SLIP','BANK_TRANSFER','CASH','CHECK','CREDIT_CARD','DEBIT_CARD','PIX') not null,
        primary key (id)
    );

    create table tb_phone (
        client_id bigint,
        id bigint generated by default as identity,
        number varchar(255) not null,
        type enum ('CELULAR','FIXO','OUTRO','WHATSAPP') not null,
        primary key (id)
    );

    create table tb_price (
        m3volume integer not null,
        price float(53) not null,
        category_id bigint,
        id bigint generated by default as identity,
        primary key (id)
    );

    create table tb_product (
        category_id bigint,
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    create table tb_product_supplier (
        cost_for5cubic_meters float(53) not null,
        cost_per_cubic_meter float(53) not null,
        density float(53) not null,
        ton_cost float(53) not null,
        id bigint generated by default as identity,
        product_id bigint,
        supplier_id bigint,
        observations varchar(255),
        primary key (id)
    );

    create table tb_settings (
        id bigint not null,
        business_img_name varchar(255),
        business_name varchar(255) not null,
        primary key (id)
    );

    create table tb_stock (
        density float(53),
        m3quantity float(53) not null,
        ton_quantity float(53) not null,
        id bigint generated by default as identity,
        product_id bigint unique,
        version bigint,
        primary key (id)
    );

    create table tb_supplier (
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id)
    );

    create table tb_user (
        admin boolean,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        first_name varchar(255) not null,
        img_name varchar(255),
        last_name varchar(255) not null,
        password varchar(255) not null,
        username varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists tb_address 
       add constraint FKmgkeodciwq4rofwws5m08v1yh 
       foreign key (client_id) 
       references tb_client;

    alter table if exists tb_fuel 
       add constraint FK5yca114jwhbc83jjghj4u9yf9 
       foreign key (expense_id) 
       references tb_expense;

    alter table if exists tb_order 
       add constraint FK7c9of0p9ogx0w8sfrebt4n9kk 
       foreign key (client_id) 
       references tb_client;

    alter table if exists tb_order 
       add constraint FKsga7o5cimuognsexkhgro0dak 
       foreign key (address_id) 
       references tb_order_address;

    alter table if exists tb_order 
       add constraint FKse6ptij0s2pp2nnbji87ivv46 
       foreign key (product_id) 
       references tb_product;

    alter table if exists tb_payment 
       add constraint FKokaf4il2cwit4h780c25dv04r 
       foreign key (order_id) 
       references tb_order;

    alter table if exists tb_phone 
       add constraint FK9bn3n1ykkraxjaw5y2qpqmby 
       foreign key (client_id) 
       references tb_client;

    alter table if exists tb_price 
       add constraint FKs94hpi9urs4n00nqd02peg4ys 
       foreign key (category_id) 
       references tb_category;

    alter table if exists tb_product 
       add constraint FK8i0sq9mfbpsrabrm2pum9fspo 
       foreign key (category_id) 
       references tb_category;

    alter table if exists tb_product_supplier 
       add constraint FKhm9dbkht6uggfk477bmuhlkq4 
       foreign key (product_id) 
       references tb_product;

    alter table if exists tb_product_supplier 
       add constraint FKsuny6mdqxe9u2mkikv5eudgor 
       foreign key (supplier_id) 
       references tb_supplier;

    alter table if exists tb_stock 
       add constraint FKrfkerq4he7y1d1rj97u8c77sf 
       foreign key (product_id) 
       references tb_product;
